### ISSUE TITLE
My TargetID still displays name off the bar

### ISSUE THREAD

**Issue by Johnny1023** [Yttrium-tYcLief/yayahud#11]
After checking the readme.md and modifying the textinsetx under TargetNameLabel to 10, it still displays the text off the bar, please offer a solution. (Maybe support for 1366x768.)

**Comment by Yttrium-tYcLief** [comment]
I don't support floating TargetID and health anymore, sorry. Too much of a UI nightmare. Just haven't gotten around to removing it from the readme.md.
