### ISSUE TITLE
White tagetID

### ISSUE THREAD

**Issue by duckarooduck** [Yttrium-tYcLief/yayahud#4]
When I look at a player (targetID) it has a white title instead of black on a gray background. Within the hud i disabled health animation and I added FLV Blu to the customization. You can comment here or add me here http://steamcommunity.com/id/mr_scales/

**Comment by duckarooduck** [comment]
like this http://i.imgur.com/ntJh4zk.jpg

**Comment by Yttrium-tYcLief** [comment]
I believe I fixed this awhile back. If it still happens then feel free to re-open or let me know on the thread.
