### ISSUE TITLE
Invasion and Gun Mettle coin animation on scoreboard

### ISSUE THREAD

**Issue by helloterence** [Yttrium-tYcLief/yayahud#5]
Invasion and Gun Mettle coin animation on scoreboard do not seem to be presented correctly. See image.
![2015-10-08_00001](https://cloud.githubusercontent.com/assets/8483175/10378596/c3ad31ae-6dd7-11e5-9a68-5d5f6fa56a2a.jpg)

**Comment by Yttrium-tYcLief** [comment]
Known issue that I feel is only really going to be easy to fix with a slight scoreboard redesign, since it happens in MvM too, and fixing it for regular play messes up the MvM scoreboard too much.

**Comment by Yttrium-tYcLief** [comment]
Decided to compromise the MvM scoreboard in order to fix this on the regular one.
