### ISSUE TITLE
Mvm loot screen

### ISSUE THREAD

**Issue by PJ228** [Yttrium-tYcLief/yayahud#9]
Everytime in mvm at the end of the round when i get my loot it doesnt show the normal loot screen its just a plain small white screen and it say Mann Vs Machine just above it. My aspect ratio is 4:3 btw

**Comment by Yttrium-tYcLief** [comment]
Can you take a screenshot of what this looks like? Does it happen in non-4:3 aspect ratios for you, or is it just a 4:3 thing?
